const USER = [
  {
    id: 1,
    username: "@adamsakea",
    password: "1234",
    token: "awdifjwaopdkpawok",
    data: {
      name: "Adam Sake Arfansyah",
      email: "adam@mail.com",
      bio: "Hello my name is adam sake arfansyah, thank you so much!",
      about: `about panjaaanng`,
      followers: 110000,
      following: 1000,
      profile_img: {
        background: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
        user: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
      },
      article: [
        {
          id: 4124536,
          title: "Resmi IPO, VKTR Andalkan Bisnis Suplai Kendaraan Listrik",
          articleDescription: `PT VKTR Teknologi Mobilitas Tbk. (VKTR)–perusahaan yang bergerak di sektor perdagangan kendaraan listrik berbasis baterai–memilih model bisnis ke pemerintah (B2G) dan emiten lainnya (B2B) sebagai roda bisnis utamanya. Perusahaan tersebut kini tengah menyasar segmen B2G dengan menyuplai permintaan kendaraan listrik, salah satunya adalah bus listrik. Bisnis suplai bus listrik ini dianggap menjanjikan mengingat operator moda transportasi besar seperti TransJakarta sebelumnya berencana bakal mengoperasikan 10.000 bus listrik hingga 2030 mendatang. Tahun 2022 lalu, anak perusahaan grup Bakrie tersebut sebelumnya telah menandatangani nota kesepahaman dengan TransJakarta untuk mengubah sekitar 3.000 unit bus diesel menjadi listrik (retrofit). Hingga akhir Mei 2023, Kontan melaporkan pihak VKTR telah memasok lebih dari 52 unit bus kepada TransJakarta. “Kita ingin kontribusi di Transjakarta lebih banyak lagi, karena Transjakarta menargetkan 10 ribu bus pada akhir tahun 2030. Jadi semaksimal mungkin kita bisa berkontribusi, kita usahakan,” kata Direktur Utama VKTR Gilarsi W. Setijono sebagaimana dikutip dari Viva.`,
          topic: ["Programming", "World"],
          createdAt: "20 June 2023",
          img: {
            banner: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img1: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img2: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
          },
        },
      ],
      lists: [],
      books: [],
    },
  },
  {
    id: 2,
    username: "@palma",
    password: "1234",
    data: {
      name: "Palma Aulia Imama",
      email: "palma@mail.com",
      bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum repellendus, odio adipisci mollitia quod, ad commodi minus nihil enim dignissimos tenetur officiis. Explicabo, quisquam. Odit vitae voluptatem minus adipisci delectus!",
      about: `about panjaaanng`,
      followers: 800,
      following: 100,
      profile_img: {
        background: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
        user: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
      },
      article: [
        {
          id: 43423,
          title: "Resmi IPO, VKTR Andalkan Bisnis Suplai Kendaraan Listrik",
          articleDescription: `PT VKTR Teknologi Mobilitas Tbk. (VKTR)–perusahaan yang bergerak di sektor perdagangan kendaraan listrik berbasis baterai–memilih model bisnis ke pemerintah (B2G) dan emiten lainnya (B2B) sebagai roda bisnis utamanya. Perusahaan tersebut kini tengah menyasar segmen B2G dengan menyuplai permintaan kendaraan listrik, salah satunya adalah bus listrik. Bisnis suplai bus listrik ini dianggap menjanjikan mengingat operator moda transportasi besar seperti TransJakarta sebelumnya berencana bakal mengoperasikan 10.000 bus listrik hingga 2030 mendatang. Tahun 2022 lalu, anak perusahaan grup Bakrie tersebut sebelumnya telah menandatangani nota kesepahaman dengan TransJakarta untuk mengubah sekitar 3.000 unit bus diesel menjadi listrik (retrofit). Hingga akhir Mei 2023, Kontan melaporkan pihak VKTR telah memasok lebih dari 52 unit bus kepada TransJakarta. “Kita ingin kontribusi di Transjakarta lebih banyak lagi, karena Transjakarta menargetkan 10 ribu bus pada akhir tahun 2030. Jadi semaksimal mungkin kita bisa berkontribusi, kita usahakan,” kata Direktur Utama VKTR Gilarsi W. Setijono sebagaimana dikutip dari Viva.`,
          topic: ["Relationship", "Software Development"],
          createdAt: "20 June 2023",
          img: {
            banner: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img1: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img2: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
          },
        },
        {
          id: 213455,
          title: "Resmi IPO, VKTR Andalkan Bisnis Suplai Kendaraan Listrik",
          articleDescription: `PT VKTR Teknologi Mobilitas Tbk. (VKTR)–perusahaan yang bergerak di sektor perdagangan kendaraan listrik berbasis baterai–memilih model bisnis ke pemerintah (B2G) dan emiten lainnya (B2B) sebagai roda bisnis utamanya. Perusahaan tersebut kini tengah menyasar segmen B2G dengan menyuplai permintaan kendaraan listrik, salah satunya adalah bus listrik. Bisnis suplai bus listrik ini dianggap menjanjikan mengingat operator moda transportasi besar seperti TransJakarta sebelumnya berencana bakal mengoperasikan 10.000 bus listrik hingga 2030 mendatang. Tahun 2022 lalu, anak perusahaan grup Bakrie tersebut sebelumnya telah menandatangani nota kesepahaman dengan TransJakarta untuk mengubah sekitar 3.000 unit bus diesel menjadi listrik (retrofit). Hingga akhir Mei 2023, Kontan melaporkan pihak VKTR telah memasok lebih dari 52 unit bus kepada TransJakarta. “Kita ingin kontribusi di Transjakarta lebih banyak lagi, karena Transjakarta menargetkan 10 ribu bus pada akhir tahun 2030. Jadi semaksimal mungkin kita bisa berkontribusi, kita usahakan,” kata Direktur Utama VKTR Gilarsi W. Setijono sebagaimana dikutip dari Viva.`,
          topic: ["Relationship", "Love", "Web Development", "Frameworks"],
          createdAt: "20 June 2023",
          img: {
            banner: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img1: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img2: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
          },
        },
        {
          id: 50396,
          title: "Resmi IPO, VKTR Andalkan Bisnis Suplai Kendaraan Listrik",
          articleDescription: `PT VKTR Teknologi Mobilitas Tbk. (VKTR)–perusahaan yang bergerak di sektor perdagangan kendaraan listrik berbasis baterai–memilih model bisnis ke pemerintah (B2G) dan emiten lainnya (B2B) sebagai roda bisnis utamanya. Perusahaan tersebut kini tengah menyasar segmen B2G dengan menyuplai permintaan kendaraan listrik, salah satunya adalah bus listrik. Bisnis suplai bus listrik ini dianggap menjanjikan mengingat operator moda transportasi besar seperti TransJakarta sebelumnya berencana bakal mengoperasikan 10.000 bus listrik hingga 2030 mendatang. Tahun 2022 lalu, anak perusahaan grup Bakrie tersebut sebelumnya telah menandatangani nota kesepahaman dengan TransJakarta untuk mengubah sekitar 3.000 unit bus diesel menjadi listrik (retrofit). Hingga akhir Mei 2023, Kontan melaporkan pihak VKTR telah memasok lebih dari 52 unit bus kepada TransJakarta. “Kita ingin kontribusi di Transjakarta lebih banyak lagi, karena Transjakarta menargetkan 10 ribu bus pada akhir tahun 2030. Jadi semaksimal mungkin kita bisa berkontribusi, kita usahakan,” kata Direktur Utama VKTR Gilarsi W. Setijono sebagaimana dikutip dari Viva.`,
          topic: ["Relationship", "Love", "Web Development", "Frameworks"],
          createdAt: "20 June 2023",
          img: {
            banner: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img1: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img2: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
          },
        },
        {
          id: 455332,
          title: "Resmi IPO, VKTR Andalkan Bisnis Suplai Kendaraan Listrik",
          articleDescription: `PT VKTR Teknologi Mobilitas Tbk. (VKTR)–perusahaan yang bergerak di sektor perdagangan kendaraan listrik berbasis baterai–memilih model bisnis ke pemerintah (B2G) dan emiten lainnya (B2B) sebagai roda bisnis utamanya. Perusahaan tersebut kini tengah menyasar segmen B2G dengan menyuplai permintaan kendaraan listrik, salah satunya adalah bus listrik. Bisnis suplai bus listrik ini dianggap menjanjikan mengingat operator moda transportasi besar seperti TransJakarta sebelumnya berencana bakal mengoperasikan 10.000 bus listrik hingga 2030 mendatang. Tahun 2022 lalu, anak perusahaan grup Bakrie tersebut sebelumnya telah menandatangani nota kesepahaman dengan TransJakarta untuk mengubah sekitar 3.000 unit bus diesel menjadi listrik (retrofit). Hingga akhir Mei 2023, Kontan melaporkan pihak VKTR telah memasok lebih dari 52 unit bus kepada TransJakarta. “Kita ingin kontribusi di Transjakarta lebih banyak lagi, karena Transjakarta menargetkan 10 ribu bus pada akhir tahun 2030. Jadi semaksimal mungkin kita bisa berkontribusi, kita usahakan,” kata Direktur Utama VKTR Gilarsi W. Setijono sebagaimana dikutip dari Viva.`,
          topic: ["Relationship", "Love", "Web Development", "Frameworks"],
          createdAt: "20 June 2023",
          img: {
            banner: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img1: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img2: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
          },
        },
      ],
      lists: [],
      books: [],
    },
  },
  {
    id: 3,
    username: "@annisamutia",
    password: "1234",
    data: {
      name: "Annisa Mutia",
      email: "annisam@mail.com",
      bio: "Hello my name is Annsa Mutia, thank you so much!",
      about: `about panjaaanng`,
      followers: 10000,
      following: 1000,
      profile_img: {
        background: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
        user: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
      },
      article: [
        {
          id: 121039,
          title: "Resmi IPO, VKTR Andalkan Bisnis Suplai Kendaraan Listrik",
          articleDescription: `PT VKTR Teknologi Mobilitas Tbk. (VKTR)–perusahaan yang bergerak di sektor perdagangan kendaraan listrik berbasis baterai–memilih model bisnis ke pemerintah (B2G) dan emiten lainnya (B2B) sebagai roda bisnis utamanya. Perusahaan tersebut kini tengah menyasar segmen B2G dengan menyuplai permintaan kendaraan listrik, salah satunya adalah bus listrik. Bisnis suplai bus listrik ini dianggap menjanjikan mengingat operator moda transportasi besar seperti TransJakarta sebelumnya berencana bakal mengoperasikan 10.000 bus listrik hingga 2030 mendatang. Tahun 2022 lalu, anak perusahaan grup Bakrie tersebut sebelumnya telah menandatangani nota kesepahaman dengan TransJakarta untuk mengubah sekitar 3.000 unit bus diesel menjadi listrik (retrofit). Hingga akhir Mei 2023, Kontan melaporkan pihak VKTR telah memasok lebih dari 52 unit bus kepada TransJakarta. “Kita ingin kontribusi di Transjakarta lebih banyak lagi, karena Transjakarta menargetkan 10 ribu bus pada akhir tahun 2030. Jadi semaksimal mungkin kita bisa berkontribusi, kita usahakan,” kata Direktur Utama VKTR Gilarsi W. Setijono sebagaimana dikutip dari Viva.`,
          topic: ["World", "Relationship"],
          createdAt: "20 June 2023",
          img: {
            banner: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img1: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img2: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
          },
        },
      ],
      lists: [],
      books: [],
    },
  },
  {
    id: 4,
    username: "@titeayu",
    password: "1234",
    data: {
      name: "Tite Ayu",
      email: "titeayu@mail.com",
      bio: "Hello my name is Tite Ayu, thank you so much!",
      about: `about panjaaanng`,
      followers: 1200,
      following: 1000,
      profile_img: {
        background: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
        user: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
      },
      article: [
        {
          id: 102345,
          title: "Resmi IPO, VKTR Andalkan Bisnis Suplai Kendaraan Listrik",
          articleDescription: `PT VKTR Teknologi Mobilitas Tbk. (VKTR)–perusahaan yang bergerak di sektor perdagangan kendaraan listrik berbasis baterai–memilih model bisnis ke pemerintah (B2G) dan emiten lainnya (B2B) sebagai roda bisnis utamanya. Perusahaan tersebut kini tengah menyasar segmen B2G dengan menyuplai permintaan kendaraan listrik, salah satunya adalah bus listrik. Bisnis suplai bus listrik ini dianggap menjanjikan mengingat operator moda transportasi besar seperti TransJakarta sebelumnya berencana bakal mengoperasikan 10.000 bus listrik hingga 2030 mendatang. Tahun 2022 lalu, anak perusahaan grup Bakrie tersebut sebelumnya telah menandatangani nota kesepahaman dengan TransJakarta untuk mengubah sekitar 3.000 unit bus diesel menjadi listrik (retrofit). Hingga akhir Mei 2023, Kontan melaporkan pihak VKTR telah memasok lebih dari 52 unit bus kepada TransJakarta. “Kita ingin kontribusi di Transjakarta lebih banyak lagi, karena Transjakarta menargetkan 10 ribu bus pada akhir tahun 2030. Jadi semaksimal mungkin kita bisa berkontribusi, kita usahakan,” kata Direktur Utama VKTR Gilarsi W. Setijono sebagaimana dikutip dari Viva.`,
          topic: ["Relationship", "News"],
          createdAt: "20 June 2023",
          img: {
            banner: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img1: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img2: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
          },
        },
        {
          id: 99999,
          title: "Resmi IPO, VKTR Andalkan Bisnis Suplai Kendaraan Listrik",
          articleDescription: `PT VKTR Teknologi Mobilitas Tbk. (VKTR)–perusahaan yang bergerak di sektor perdagangan kendaraan listrik berbasis baterai–memilih model bisnis ke pemerintah (B2G) dan emiten lainnya (B2B) sebagai roda bisnis utamanya. Perusahaan tersebut kini tengah menyasar segmen B2G dengan menyuplai permintaan kendaraan listrik, salah satunya adalah bus listrik. Bisnis suplai bus listrik ini dianggap menjanjikan mengingat operator moda transportasi besar seperti TransJakarta sebelumnya berencana bakal mengoperasikan 10.000 bus listrik hingga 2030 mendatang. Tahun 2022 lalu, anak perusahaan grup Bakrie tersebut sebelumnya telah menandatangani nota kesepahaman dengan TransJakarta untuk mengubah sekitar 3.000 unit bus diesel menjadi listrik (retrofit). Hingga akhir Mei 2023, Kontan melaporkan pihak VKTR telah memasok lebih dari 52 unit bus kepada TransJakarta. “Kita ingin kontribusi di Transjakarta lebih banyak lagi, karena Transjakarta menargetkan 10 ribu bus pada akhir tahun 2030. Jadi semaksimal mungkin kita bisa berkontribusi, kita usahakan,” kata Direktur Utama VKTR Gilarsi W. Setijono sebagaimana dikutip dari Viva.`,
          topic: ["Self Improvement", "Software Development"],
          createdAt: "20 June 2023",
          img: {
            banner: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img1: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img2: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
          },
        },
      ],
      lists: [],
      books: [],
    },
  },
  {
    id: 5,
    username: "@rianiprameswari",
    password: "1234",
    data: {
      name: "Riani Prameswari",
      email: "rianiprameswari@mail.com",
      bio: "Hello my name is Riani Prameswari, thank you so much!",
      about: `about panjaaanng`,
      followers: 1200,
      following: 1000,
      profile_img: {
        background: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
        user: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
      },
      article: [
        {
          id: 102345,
          title: "Resmi IPO, VKTR Andalkan Bisnis Suplai Kendaraan Listrik",
          articleDescription: `PT VKTR Teknologi Mobilitas Tbk. (VKTR)–perusahaan yang bergerak di sektor perdagangan kendaraan listrik berbasis baterai–memilih model bisnis ke pemerintah (B2G) dan emiten lainnya (B2B) sebagai roda bisnis utamanya. Perusahaan tersebut kini tengah menyasar segmen B2G dengan menyuplai permintaan kendaraan listrik, salah satunya adalah bus listrik. Bisnis suplai bus listrik ini dianggap menjanjikan mengingat operator moda transportasi besar seperti TransJakarta sebelumnya berencana bakal mengoperasikan 10.000 bus listrik hingga 2030 mendatang. Tahun 2022 lalu, anak perusahaan grup Bakrie tersebut sebelumnya telah menandatangani nota kesepahaman dengan TransJakarta untuk mengubah sekitar 3.000 unit bus diesel menjadi listrik (retrofit). Hingga akhir Mei 2023, Kontan melaporkan pihak VKTR telah memasok lebih dari 52 unit bus kepada TransJakarta. “Kita ingin kontribusi di Transjakarta lebih banyak lagi, karena Transjakarta menargetkan 10 ribu bus pada akhir tahun 2030. Jadi semaksimal mungkin kita bisa berkontribusi, kita usahakan,” kata Direktur Utama VKTR Gilarsi W. Setijono sebagaimana dikutip dari Viva.`,
          topic: ["Relationship", "News"],
          createdAt: "20 June 2023",
          img: {
            banner: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img1: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img2: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
          },
        },
        {
          id: 99999,
          title: "Resmi IPO, VKTR Andalkan Bisnis Suplai Kendaraan Listrik",
          articleDescription: `PT VKTR Teknologi Mobilitas Tbk. (VKTR)–perusahaan yang bergerak di sektor perdagangan kendaraan listrik berbasis baterai–memilih model bisnis ke pemerintah (B2G) dan emiten lainnya (B2B) sebagai roda bisnis utamanya. Perusahaan tersebut kini tengah menyasar segmen B2G dengan menyuplai permintaan kendaraan listrik, salah satunya adalah bus listrik. Bisnis suplai bus listrik ini dianggap menjanjikan mengingat operator moda transportasi besar seperti TransJakarta sebelumnya berencana bakal mengoperasikan 10.000 bus listrik hingga 2030 mendatang. Tahun 2022 lalu, anak perusahaan grup Bakrie tersebut sebelumnya telah menandatangani nota kesepahaman dengan TransJakarta untuk mengubah sekitar 3.000 unit bus diesel menjadi listrik (retrofit). Hingga akhir Mei 2023, Kontan melaporkan pihak VKTR telah memasok lebih dari 52 unit bus kepada TransJakarta. “Kita ingin kontribusi di Transjakarta lebih banyak lagi, karena Transjakarta menargetkan 10 ribu bus pada akhir tahun 2030. Jadi semaksimal mungkin kita bisa berkontribusi, kita usahakan,” kata Direktur Utama VKTR Gilarsi W. Setijono sebagaimana dikutip dari Viva.`,
          topic: ["Self Improvement", "Software Development"],
          createdAt: "20 June 2023",
          img: {
            banner: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img1: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
            img2: "https://raw.githubusercontent.com/Damskuuii/image/main/esteh.jpeg",
          },
        },
      ],
      lists: [],
      books: [],
    },
  },
];

export default USER;
